### Get the root endpoint
GET http://localhost:3030/
Content-Type: application/json

### Get the root endpoint
GET http://localhost:3030/users
Content-Type: application/json

### Get the root endpoint
GET http://localhost:3030/users/684d94f7287a2e9c1e29f290
Content-Type: application/json

### Get the root endpoint
POST http://localhost:3030/users HTTP/1.1
Content-Type: application/json

{
    "name": "Natasha Chilumba",
    "email": "natashachilumba099@gmail.com",
    "role": "Nurse"
}

### Get the root endpoint
PUT http://localhost:3030/users/684dd3b0d2e3c1e68bc42bbf HTTP/1.1
Content-Type: application/json

{
   "name": "Natasha Nalavwe Chilumba",
    "email": "natashachilumba099@gmail.com",
    "role": "Mid-Wife"
}

### Get the root endpoint
DELETE http://localhost:3030/users/684dd3b0d2e3c1e68bc42bbf
Content-Type: application/json

### Get the root endpoint
GET http://localhost:3030/patient
Content-Type: application/json

### Get the root endpoint
GET http://localhost:3030/patient/684d567cd0e335b500e0552f
Content-Type: application/json

### Get the root endpoint
POST http://localhost:3030/patient HTTP/1.1
Content-Type: application/json

{
    "fName": "Lloyd",
    "lName": "Mununga",
    "birthdate": "15/01/1997",
    "maritalStatus": "Single",
    "contact": "07770077336",
    "email": "lloydm@gmail.com",
    "caseHistory": "Health History Report (Male, Age 28). The patient is a 28-year-old male with a history of mild asthma since childhood and a prior episode of gastritis in his early twenties. He reports occasional fatigue and stress-related headaches. No current medications. Vital signs are stable; overall health is fair with no major ongoing conditions"
}

### Get the root endpoint
PUT http://localhost:3030/patient/684dda46cbf8168dbb8ce129 HTTP/1.1
Content-Type: application/json

{
    "fName": "Lloyd Kaumba",
    "lName": "Mununga",
    "birthdate": "15/01/1997",
    "maritalStatus": "Single",
    "contact": "07770077336",
    "email": "lloydm@gmail.com",
    "caseHistory": "Health History. The patient is a 28-year-old male with a history of mild asthma since childhood and a prior episode of gastritis in his early twenties. He reports occasional fatigue and stress-related headaches. No current medications. Vital signs are stable; overall health is fair with no major ongoing conditions"
}

### Get the root endpoint
DELETE http://localhost:3030/patient/684dda46cbf8168dbb8ce129
Content-Type: application/json
